apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mongodbbackups.mongodb.erikvancraddock.com
spec:
  group: mongodb.erikvancraddock.com
  names:
    kind: MongoDbBackup
    listKind: MongoDbBackupList
    plural: mongodbbackups
    singular: mongodbbackup
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
